// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 27/03/2026 11:31:00
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/wamp64/www/works/chemists-club-hotel-data/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/templates/template1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/templates/template3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/templates/template2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/plugins/**/*.{js,ts,mjs}","C:/wamp64/www/works/chemists-club-hotel-data/composables/**/*.{js,ts,mjs}","C:/wamp64/www/works/chemists-club-hotel-data/utils/**/*.{js,ts,mjs}","C:/wamp64/www/works/chemists-club-hotel-data/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/chemists-club-hotel-data/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;