// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/04/2026 17:18:19
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/wamp64/www/works/ratematch-websites/rate-match-websites/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/templates/template1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/templates/template3/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/templates/template2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/plugins/**/*.{js,ts,mjs}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/composables/**/*.{js,ts,mjs}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/utils/**/*.{js,ts,mjs}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/wamp64/www/works/ratematch-websites/rate-match-websites/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;